### ISSUE TITLE
Erro in IOP

### ISSUE THREAD

**Issue by vitorgamer58** [Brexchange/Brexchange#5]
```
I, [2018-06-21T21:13:05.357680 #15573]  INFO -- :   Rendered shared/_footer.html.slim (0.0ms)
I, [2018-06-21T21:13:05.358009 #15573]  INFO -- : Completed 200 OK in 142ms (Views: 114.5ms | ActiveRecord: 8.2ms)
I, [2018-06-21T21:13:06.726495 #15573]  INFO -- : Started GET "/exchange_assets" for 108.162.212.220 at 2018-06-21 21:13:06 +0000
I, [2018-06-21T21:13:06.732082 #15573]  INFO -- : Processing by Private::AssetsController#index as HTML
I, [2018-06-21T21:13:06.785928 #15573]  INFO -- :   Rendered private/assets/_liability_data.html.slim (13.4ms)
I, [2018-06-21T21:13:06.786818 #15573]  INFO -- :   Rendered private/assets/_liability_tabs.html.slim (19.7ms)
I, [2018-06-21T21:13:06.786899 #15573]  INFO -- :   Rendered private/assets/_liability_proof.html.slim (23.3ms)
I, [2018-06-21T21:13:06.786972 #15573]  INFO -- :   Rendered private/assets/index.html.slim within layouts/application (28.9ms)
I, [2018-06-21T21:13:06.787135 #15573]  INFO -- : Completed 500 Internal Server Error in 55ms
F, [2018-06-21T21:13:06.788371 #15573] FATAL -- :
ActionView::Template::Error (undefined method `sum' for nil:NilClass):
    19:         span.title = t('.iop-assets-total')
    20:         span.currency
    21:           == t("currency.icon.iop")
    22:           = @iop_proof.sum
    23:       = render 'liability_data', account: @iop_account, proof: @iop_proof
    24:
    25:     #cny-proof.tab-pane:        .trade-wrapper
  app/views/private/assets/_liability_tabs.html.slim:22:in `_app_views_private_assets__liability_tabs_html_slim__2306003416895593491_46988864952060'
  app/views/private/assets/_liability_proof.html.slim:10:in `_app_views_private_assets__liability_proof_html_slim___2646039863397537389_46988865456120'
  app/views/private/assets/index.html.slim:14:in `block in _app_views_private_assets_index_html_slim__3192930992893342426_46988866367420'
  app/views/private/assets/index.html.slim:1:in `_app_views_private_assets_index_html_slim__3192930992893342426_46988866367420'
  lib/middleware/security.rb:11:in `call'

```

**Comment by vitorgamer58** [comment]
```
deploy@instance-2:~$ cd peatio/current
deploy@instance-2:~/peatio/current$ bundle exec rails server
=> Booting WEBrick
=> Rails 4.0.12 application starting in production on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Exiting
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/psych.rb:370:in `parse': (/home/deploy/peatio/current/config/currencies.yml): found character that cannot start any token while scanning for the next token at line 60 column 1 (Psych::SyntaxError)
```
https://github.com/Brexchange/Brexchange/blob/stable/config/currencies.yml.example#L60

**Comment by vitorgamer58** [comment]
partiality Solved
log production.log
```
I, [2018-06-23T12:11:11.153120 #19244]  INFO -- :   Rendered private/assets/_liability_data.html.slim (2.6ms)
I, [2018-06-23T12:11:11.155930 #19244]  INFO -- :   Rendered private/assets/_liability_data.html.slim (2.4ms)
I, [2018-06-23T12:11:11.155988 #19244]  INFO -- :   Rendered private/assets/_liability_tabs.html.slim (24.1ms)
I, [2018-06-23T12:11:11.156023 #19244]  INFO -- :   Rendered private/assets/_liability_proof.html.slim (27.3ms)
I, [2018-06-23T12:11:11.176611 #19244]  INFO -- :   Rendered private/assets/_btc_assets.html.slim (5.0ms)
I, [2018-06-23T12:11:11.199725 #19244]  INFO -- :   Rendered private/assets/_iop_assets.html.slim (5.2ms)
I, [2018-06-23T12:11:11.206013 #19244]  INFO -- :   Rendered private/assets/index.html.slim within layouts/application (82.0ms)
I, [2018-06-23T12:11:11.206218 #19244]  INFO -- : Completed 500 Internal Server Error in 107ms
F, [2018-06-23T12:11:11.207263 #19244] FATAL -- :
ActionView::Template::Error (Missing partial private/assets/nbr_assets, private/base/nbr_assets, application/nbr_assets with {:locale=>[:"pt-BR", :pt, :en],$
  * "/home/deploy/peatio/current/app/views"
  * "/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/kaminari-0.15.1/app/views"
  * "/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/datagrid-1.0.5/app/views"
  * "/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/doorkeeper-1.4.1/app/views"
):
    15:
    16:     div data-scroll-index=1 = render 'btc_assets'
    17:     div data-scroll-index=1 = render 'iop_assets'
    18:     div data-scroll-index=1 = render 'nbr_assets'
    19:     div data-scroll-index=2 = render 'cny_assets'
  app/views/private/assets/index.html.slim:18:in `block in _app_views_private_assets_index_html_slim__4541057259268021289_47136598673220'
  app/views/private/assets/index.html.slim:1:in `_app_views_private_assets_index_html_slim__4541057259268021289_47136598673220'
  lib/middleware/security.rb:11:in `call'

```

**Comment by vitorgamer58** [comment]
SOLVED
with the IOP it was just a tab in configs / currencies.yml and with the NBR it's just lacking configuration.
Refer to https://github.com/peatio/peatio/issues/588

**Comment by vitorgamer58** [comment]
**IOP WITHDRAW NOT WORKS**
```
I, [2018-07-11T17:17:28.974415 #3892]  INFO -- : Started POST "/withdraws/fermats" for 108.162.212.178 at 2018-07-11 17:17:28 +0000
I, [2018-07-11T17:17:28.976095 #3892]  INFO -- : Processing by Private::Withdraws::FermatsController#create as HTML
I, [2018-07-11T17:17:28.976188 #3892]  INFO -- :   Parameters: {"withdraw"=>{"member_id"=>5, "currency"=>"iop", "sum"=>0.499, "fund_source"=>5}, "two_factor"=>{"type"=>"app", "otp"=>"268683"}, "fermat"=>{"withdraw"=>{"member_id"=>5, "currency"=>"iop", "sum"=>0.499, "fund_source"=>5}, "two_factor"=>{"type"=>"app", "otp"=>"268683"}}}
I, [2018-07-11T17:17:28.999598 #3892]  INFO -- :   Rendered text template (0.0ms)
I, [2018-07-11T17:17:28.999791 #3892]  INFO -- : Completed 403 Forbidden in 24ms (Views: 0.4ms | ActiveRecord: 4.9ms)
```

**Comment by vitorgamer58** [comment]
```
I, [2018-07-11T17:35:56.002348 #3892]  INFO -- : Started POST "/withdraws/fermats" for 108.162.212.178 at 2018-07-11 17:35:56 +0000
I, [2018-07-11T17:35:56.004292 #3892]  INFO -- : Processing by Private::Withdraws::FermatsController#create as HTML
I, [2018-07-11T17:35:56.004375 #3892]  INFO -- :   Parameters: {"withdraw"=>{"member_id"=>5, "currency"=>"iop", "sum"=>0.5, "fund_source"=>5}, "two_factor"=>{"type"=>"app", "otp"=>"657112"}, "fermat"=>{"withdraw"=>{"member_id"=>5, "currency"=>"iop", "sum"=>0.5, "fund_source"=>5}, "two_factor"=>{"type"=>"app", "otp"=>"657112"}}}
I, [2018-07-11T17:35:56.107103 #3892]  INFO -- :   Rendered text template (0.0ms)
I, [2018-07-11T17:35:56.107434 #3892]  INFO -- : Completed 200 OK in 103ms (Views: 0.5ms | ActiveRecord: 61.9ms)
I, [2018-07-11T17:35:56.117022 #29232]  INFO -- :   Rendered withdraw_mailer/submitted.html.erb within layouts/mailers/application (1.2ms)
I, [2018-07-11T17:35:56.263110 #3892]  INFO -- : Started GET "/two_factors/app" for 108.162.212.178 at 2018-07-11 17:35:56 +0000
I, [2018-07-11T17:35:56.264989 #3892]  INFO -- : Processing by TwoFactorsController#show as HTML
I, [2018-07-11T17:35:56.265055 #3892]  INFO -- :   Parameters: {"id"=>"app"}
I, [2018-07-11T17:35:56.277284 #3892]  INFO -- :   Rendered text template (0.0ms)
I, [2018-07-11T17:35:56.277493 #3892]  INFO -- : Completed 200 OK in 12ms (Views: 0.5ms | ActiveRecord: 1.0ms)
I, [2018-07-11T17:35:57.134517 #29232]  INFO -- : 
Sent mail to totalmixvariedades@gmail.com (1016.4ms)
```
a reboot in all Peatio daemons seems to have solved the 403 error problem, but the loot still does not work.

**Comment by vitorgamer58** [comment]
for some reason it sufficed for me to exchange a number for ZERO withdraw worked.
in config/currencies.yml
`  quick_withdraw_max: 0`
and then I logged into the admin account and approved the withdraw, it was done without problems.
![Admin Panel](https://raw.githubusercontent.com/vitorgamer58/vitorgamer58-images/master/Screenshot_122.png)
![IOP-QT](https://raw.githubusercontent.com/vitorgamer58/vitorgamer58-images/master/Screenshot_123.png)
in Log
```
I, [2018-07-12T16:50:20.333538 #3892]  INFO -- : Started POST "/withdraws/fermats" for 108.162.212.178 at 2018-07-12 16:50:20 +0000
I, [2018-07-12T16:50:20.335648 #3892]  INFO -- : Processing by Private::Withdraws::FermatsController#create as HTML
I, [2018-07-12T16:50:20.335789 #3892]  INFO -- :   Parameters: {"withdraw"=>{"member_id"=>5, "currency"=>"iop", "sum"=>0.5, "fund_source"=>5}, "two_factor"=>{"type"=>"app", "otp"=>"072995"}, "fermat"=>{"withdraw"=>{"member_id"=>5, "currency"=>"iop", "sum"=>0.5, "fund_source"=>5}, "two_factor"=>{"type"=>"app", "otp"=>"072995"}}}
I, [2018-07-12T16:50:20.487761 #3892]  INFO -- :   Rendered text template (0.0ms)
I, [2018-07-12T16:50:20.488154 #3892]  INFO -- : Completed 200 OK in 152ms (Views: 0.8ms | ActiveRecord: 67.5ms)
I, [2018-07-12T16:50:20.541098 #31103]  INFO -- :   Rendered withdraw_mailer/submitted.html.erb within layouts/mailers/application (1.5ms)
I, [2018-07-12T16:50:21.534243 #31103]  INFO -- : 
Sent mail to totalmixvariedades@gmail.com (991.5ms)
I, [2018-07-12T16:50:23.526351 #3892]  INFO -- : Started GET "/funds?lang=en" for 108.162.212.178 at 2018-07-12 16:50:23 +0000
I, [2018-07-12T16:50:23.528424 #3892]  INFO -- : Processing by Private::FundsController#index as HTML
I, [2018-07-12T16:50:23.528514 #3892]  INFO -- :   Parameters: {"lang"=>"en"}
I, [2018-07-12T16:50:23.617820 #3892]  INFO -- :   Rendered private/funds/index.html.erb within layouts/funds (0.5ms)
I, [2018-07-12T16:50:23.639390 #3892]  INFO -- :   Rendered shared/_html5.html.slim (0.2ms)
I, [2018-07-12T16:50:23.640193 #3892]  INFO -- :   Rendered shared/_meta.html.slim (0.6ms)
I, [2018-07-12T16:50:23.640489 #3892]  INFO -- :   Rendered shared/_google.html (0.1ms)
I, [2018-07-12T16:50:23.640641 #3892]  INFO -- :   Rendered shared/_socialmeta.html (0.0ms)
I, [2018-07-12T16:50:23.653032 #3892]  INFO -- :   Rendered shared/_header_profile_setting.html.slim (10.4ms)
I, [2018-07-12T16:50:23.653625 #3892]  INFO -- :   Rendered shared/_header_lang_sel.html.slim (0.2ms)
I, [2018-07-12T16:50:23.653708 #3892]  INFO -- :   Rendered shared/_header.html.slim (12.7ms)
I, [2018-07-12T16:50:23.654010 #3892]  INFO -- :   Rendered shared/_footer.html.slim (0.1ms)
I, [2018-07-12T16:50:23.654371 #3892]  INFO -- : Completed 200 OK in 126ms (Views: 31.2ms | ActiveRecord: 25.5ms)
I, [2018-07-12T16:50:23.947100 #3892]  INFO -- : Started POST "/funds/gen_address" for 108.162.212.178 at 2018-07-12 16:50:23 +0000
I, [2018-07-12T16:50:23.948865 #3892]  INFO -- : Processing by Private::FundsController#gen_address as */*
I, [2018-07-12T16:50:23.980590 #3892]  INFO -- :   Rendered text template (0.0ms)
I, [2018-07-12T16:50:23.980832 #3892]  INFO -- : Completed 200 OK in 32ms (Views: 0.5ms | ActiveRecord: 10.2ms)
I, [2018-07-12T16:50:24.107346 #3892]  INFO -- : Started GET "/two_factors/app" for 108.162.212.178 at 2018-07-12 16:50:24 +0000
I, [2018-07-12T16:50:24.109233 #3892]  INFO -- : Processing by TwoFactorsController#show as HTML
I, [2018-07-12T16:50:24.109302 #3892]  INFO -- :   Parameters: {"id"=>"app"}
I, [2018-07-12T16:50:24.131112 #3892]  INFO -- :   Rendered text template (0.0ms)
I, [2018-07-12T16:50:24.131428 #3892]  INFO -- : Completed 200 OK in 22ms (Views: 0.6ms | ActiveRecord: 1.1ms)
I, [2018-07-12T16:50:24.518360 #3892]  INFO -- : Started POST "/pusher/auth" for 108.162.212.178 at 2018-07-12 16:50:24 +0000
I, [2018-07-12T16:50:24.520176 #3892]  INFO -- : Processing by Private::PusherController#auth as */*
I, [2018-07-12T16:50:24.520259 #3892]  INFO -- :   Parameters: {"socket_id"=>"241534.2731952", "channel_name"=>"private-PEAOKNLZ4BITIO"}
I, [2018-07-12T16:50:24.537334 #3892]  INFO -- : Completed 200 OK in 17ms (Views: 0.2ms | ActiveRecord: 0.5ms)
I, [2018-07-12T16:50:27.987073 #3892]  INFO -- : Started GET "/admin/withdraws/fermats" for 108.162.212.178 at 2018-07-12 16:50:27 +0000
I, [2018-07-12T16:50:27.988932 #3892]  INFO -- : Processing by Admin::Withdraws::FermatsController#index as HTML
I, [2018-07-12T16:50:28.037780 #3892]  INFO -- :   Rendered admin/withdraws/fermats/_table.html.slim (9.9ms)
I, [2018-07-12T16:50:28.051055 #3892]  INFO -- :   Rendered admin/withdraws/fermats/_table.html.slim (11.3ms)
I, [2018-07-12T16:50:28.051203 #3892]  INFO -- :   Rendered admin/withdraws/fermats/index.html.slim within layouts/admin (25.9ms)
I, [2018-07-12T16:50:28.073037 #3892]  INFO -- :   Rendered shared/_flash.slim (0.2ms)
I, [2018-07-12T16:50:28.073494 #3892]  INFO -- : Completed 200 OK in 84ms (Views: 45.7ms | ActiveRecord: 3.9ms)
I, [2018-07-12T16:50:30.413550 #3892]  INFO -- : Started GET "/admin/withdraws/fermats/18" for 108.162.212.178 at 2018-07-12 16:50:30 +0000
I, [2018-07-12T16:50:30.415235 #3892]  INFO -- : Processing by Admin::Withdraws::FermatsController#show as HTML
I, [2018-07-12T16:50:30.415301 #3892]  INFO -- :   Parameters: {"id"=>"18"}
I, [2018-07-12T16:50:30.477717 #3892]  INFO -- :   Rendered shared/admin/_member.html.slim (9.9ms)
I, [2018-07-12T16:50:30.480680 #3892]  INFO -- :   Rendered shared/admin/_account.html.slim (2.7ms)
I, [2018-07-12T16:50:30.480780 #3892]  INFO -- :   Rendered admin/withdraws/fermats/show.html.slim within layouts/admin (24.3ms)
I, [2018-07-12T16:50:30.501532 #3892]  INFO -- :   Rendered shared/_flash.slim (0.1ms)
I, [2018-07-12T16:50:30.501949 #3892]  INFO -- : Completed 200 OK in 87ms (Views: 39.4ms | ActiveRecord: 11.8ms)
I, [2018-07-12T16:50:33.040985 #3892]  INFO -- : Started PATCH "/admin/withdraws/fermats/18" for 108.162.212.178 at 2018-07-12 16:50:33 +0000
I, [2018-07-12T16:50:33.043054 #3892]  INFO -- : Processing by Admin::Withdraws::FermatsController#update as HTML
I, [2018-07-12T16:50:33.043146 #3892]  INFO -- :   Parameters: {"authenticity_token"=>"4BCuMABrMhyyfqaVZ+RzezDIXB8h27gzhSKl4VWX6+o=", "id"=>"18"}
I, [2018-07-12T16:50:33.112398 #3892]  INFO -- : Redirected to https://brexchange.br-com.net/admin/withdraws/fermats/18
I, [2018-07-12T16:50:33.112646 #3892]  INFO -- : Completed 302 Found in 69ms (ActiveRecord: 19.2ms)
I, [2018-07-12T16:50:33.134784 #31103]  INFO -- :   Rendered withdraw_mailer/processing.html.erb within layouts/mailers/application (1.1ms)
I, [2018-07-12T16:50:33.309961 #3892]  INFO -- : Started GET "/admin/withdraws/fermats/18" for 108.162.212.178 at 2018-07-12 16:50:33 +0000
I, [2018-07-12T16:50:33.312127 #3892]  INFO -- : Processing by Admin::Withdraws::FermatsController#show as HTML
I, [2018-07-12T16:50:33.312216 #3892]  INFO -- :   Parameters: {"id"=>"18"}
I, [2018-07-12T16:50:33.380420 #3892]  INFO -- :   Rendered shared/admin/_member.html.slim (8.1ms)
I, [2018-07-12T16:50:33.385074 #3892]  INFO -- :   Rendered shared/admin/_account.html.slim (3.1ms)
I, [2018-07-12T16:50:33.385191 #3892]  INFO -- :   Rendered admin/withdraws/fermats/show.html.slim within layouts/admin (22.2ms)
I, [2018-07-12T16:50:33.408735 #3892]  INFO -- :   Rendered shared/_flash.slim (0.2ms)
I, [2018-07-12T16:50:33.409259 #3892]  INFO -- : Completed 200 OK in 97ms (Views: 45.3ms | ActiveRecord: 3.4ms)
I, [2018-07-12T16:50:34.316999 #31103]  INFO -- : 
Sent mail to totalmixvariedades@gmail.com (1181.0ms)
I, [2018-07-12T16:50:38.371364 #3892]  INFO -- : Started GET "/admin/withdraws/fermats" for 108.162.212.178 at 2018-07-12 16:50:38 +0000
I, [2018-07-12T16:50:38.373083 #3892]  INFO -- : Processing by Admin::Withdraws::FermatsController#index as HTML
I, [2018-07-12T16:50:38.432614 #3892]  INFO -- :   Rendered admin/withdraws/fermats/_table.html.slim (19.7ms)
I, [2018-07-12T16:50:38.432767 #3892]  INFO -- :   Rendered admin/withdraws/fermats/index.html.slim within layouts/admin (27.7ms)
I, [2018-07-12T16:50:38.459771 #3892]  INFO -- :   Rendered shared/_flash.slim (0.1ms)
I, [2018-07-12T16:50:38.460158 #3892]  INFO -- : Completed 200 OK in 87ms (Views: 49.2ms | ActiveRecord: 7.1ms)
I, [2018-07-12T16:50:40.334793 #3892]  INFO -- : Started GET "/admin/withdraws/fermats/18" for 108.162.212.178 at 2018-07-12 16:50:40 +0000
I, [2018-07-12T16:50:40.336709 #3892]  INFO -- : Processing by Admin::Withdraws::FermatsController#show as HTML
I, [2018-07-12T16:50:40.336844 #3892]  INFO -- :   Parameters: {"id"=>"18"}
I, [2018-07-12T16:50:40.395323 #3892]  INFO -- :   Rendered shared/admin/_member.html.slim (8.5ms)
I, [2018-07-12T16:50:40.399699 #3892]  INFO -- :   Rendered shared/admin/_account.html.slim (2.6ms)
I, [2018-07-12T16:50:40.399807 #3892]  INFO -- :   Rendered admin/withdraws/fermats/show.html.slim within layouts/admin (24.9ms)
I, [2018-07-12T16:50:40.428144 #3892]  INFO -- :   Rendered shared/_flash.slim (0.1ms)
I, [2018-07-12T16:50:40.428552 #3892]  INFO -- : Completed 200 OK in 92ms (Views: 48.1ms | ActiveRecord: 12.2ms)
I, [2018-07-12T16:55:26.262433 #3892]  INFO -- : Started GET "/admin/withdraws/fermats" for 108.162.212.178 at 2018-07-12 16:55:26 +0000
I, [2018-07-12T16:55:26.264580 #3892]  INFO -- : Processing by Admin::Withdraws::FermatsController#index as HTML
I, [2018-07-12T16:55:26.326457 #3892]  INFO -- :   Rendered admin/withdraws/fermats/_table.html.slim (21.9ms)
I, [2018-07-12T16:55:26.326615 #3892]  INFO -- :   Rendered admin/withdraws/fermats/index.html.slim within layouts/admin (25.6ms)
I, [2018-07-12T16:55:26.351140 #3892]  INFO -- :   Rendered shared/_flash.slim (0.1ms)
I, [2018-07-12T16:55:26.351594 #3892]  INFO -- : Completed 200 OK in 87ms (Views: 48.4ms | ActiveRecord: 3.2ms)
I, [2018-07-12T16:57:12.579142 #3892]  INFO -- : Started GET "/" for 172.68.144.216 at 2018-07-12 16:57:12 +0000
I, [2018-07-12T16:57:12.581437 #3892]  INFO -- : Processing by WelcomeController#index as HTML
I, [2018-07-12T16:57:12.600673 #3892]  INFO -- :   Rendered welcome/index.html.slim within layouts/landing (2.8ms)
I, [2018-07-12T16:57:12.607013 #3892]  INFO -- :   Rendered shared/_html5.html.slim (0.1ms)
I, [2018-07-12T16:57:12.607977 #3892]  INFO -- :   Rendered shared/_meta.html.slim (0.7ms)
I, [2018-07-12T16:57:12.608316 #3892]  INFO -- :   Rendered shared/_google.html (0.1ms)
I, [2018-07-12T16:57:12.608567 #3892]  INFO -- :   Rendered shared/_socialmeta.html (0.0ms)
I, [2018-07-12T16:57:12.615403 #3892]  INFO -- :   Rendered shared/_alert.html.slim (0.4ms)
I, [2018-07-12T16:57:12.615747 #3892]  INFO -- :   Rendered shared/_footer.html.slim (0.1ms)
I, [2018-07-12T16:57:12.616074 #3892]  INFO -- : Completed 200 OK in 34ms (Views: 18.7ms | ActiveRecord: 0.4ms)
```
and Withdraw coin log
```
peatio:amqp:withdraw_coin: process with pid 14292 started.
I, [2018-07-07T18:12:51.918345 #14292]  INFO -- : Connected to AMQP broker (prefetch: default)
Terminating threads ..
Stopped.
peatio:amqp:withdraw_coin: process with pid 24118 started.
I, [2018-07-07T18:45:14.450884 #24118]  INFO -- : Connected to AMQP broker (prefetch: default)
Terminating threads ..
Stopped.
peatio:amqp:withdraw_coin: process with pid 1127 started.
I, [2018-07-11T12:14:36.288288 #1127]  INFO -- : Connected to AMQP broker (prefetch: default)
Terminating threads ..
Stopped.
peatio:amqp:withdraw_coin: process with pid 29303 started.
I, [2018-07-11T17:33:03.520506 #29303]  INFO -- : Connected to AMQP broker (prefetch: default)
Terminating threads ..
Stopped.
peatio:amqp:withdraw_coin: process with pid 31154 started.
I, [2018-07-12T16:46:36.086360 #31154]  INFO -- : Connected to AMQP broker (prefetch: default)
I, [2018-07-12T16:50:33.112484 #31154]  INFO -- : Received: {"id":18,"locale":"pt"}
```


this is strange and needs an investigation, we can not stay all the time approving withdraw, they have to work alone without needing human intervention.
