### ISSUE TITLE
Erro in NBR

### ISSUE THREAD

**Issue by vitorgamer58** [Brexchange/Brexchange#6]
i get this erro in log/production.log

```
I, [2018-06-23T16:54:50.571020 #10964]  INFO -- : Started GET "/exchange_assets" for 108.162.212.220 at 2018-06-23 16:54:50 +0000
I, [2018-06-23T16:54:50.573042 #10964]  INFO -- : Processing by Private::AssetsController#index as HTML
I, [2018-06-23T16:54:50.590365 #10964]  INFO -- : Completed 500 Internal Server Error in 17ms
F, [2018-06-23T16:54:50.591102 #10964] FATAL -- :
NoMethodError (undefined method `value' for nil:NilClass):
  app/models/proof.rb:15:in `current'
  app/controllers/private/assets_controller.rb:9:in `index'
  lib/middleware/security.rb:11:in `call
```

**Comment by vitorgamer58** [comment]
partially solved by exchanging NBR for nbr
now i have the same error, https://github.com/Brexchange/Brexchange/issues/5
```
I, [2018-06-24T13:58:04.558378 #32507]  INFO -- :   Rendered private/assets/_liability_data.html.slim (2.9ms)
I, [2018-06-24T13:58:04.561344 #32507]  INFO -- :   Rendered private/assets/_liability_data.html.slim (2.6ms)
I, [2018-06-24T13:58:04.562536 #32507]  INFO -- :   Rendered private/assets/_liability_tabs.html.slim (7.7ms)
I, [2018-06-24T13:58:04.562589 #32507]  INFO -- :   Rendered private/assets/_liability_proof.html.slim (8.2ms)
I, [2018-06-24T13:58:04.562653 #32507]  INFO -- :   Rendered private/assets/index.html.slim within layouts/application (8.7ms)
I, [2018-06-24T13:58:04.562752 #32507]  INFO -- : Completed 500 Internal Server Error in 38ms
F, [2018-06-24T13:58:04.563893 #32507] FATAL -- :
ActionView::Template::Error (undefined method `sum' for nil:NilClass):
    27:         span.title = t('.nbr-assets-total')
    28:         span.currency
    29:           == t("currency.icon.nbr")
    30:           = @nbr_proof.sum
    31:       = render 'liability_data', account: @nbr_account, proof: @nbr_proof
    32:
    33:     #cny-proof.tab-pane:        .trade-wrapper
  app/views/private/assets/_liability_tabs.html.slim:30:in `_app_views_private_assets__liability_tabs_html_slim___3343364873524129749_47409154158180'
  app/views/private/assets/_liability_proof.html.slim:10:in `_app_views_private_assets__liability_proof_html_slim__2673429277222368316_47409154867860'
  app/views/private/assets/index.html.slim:16:in `block in _app_views_private_assets_index_html_slim___3279802707881115037_47409157174820'
  app/views/private/assets/index.html.slim:1:in `_app_views_private_assets_index_html_slim___3279802707881115037_47409157174820'
  lib/middleware/security.rb:11:in `call'

```

**Comment by vitorgamer58** [comment]
https://github.com/gravio-net/graviex/blob/master/app/views/private/assets/_liability_tabs.html.slim

**Comment by vitorgamer58** [comment]
Solved

**Comment by gjnardoni** [comment]
Hello @vitorgamer58 : I have the same issue and I can't find a way to solve it.
Can you please point me your solution?. Thanks
